services:
  nowplaying:
    image: ghcr.io/tetra-fox/nowplaying:latest
    environment:
      LASTFM_USER: ${LASTFM_USER:?LASTFM_USER is required}
      LASTFM_API_KEY: ${LASTFM_API_KEY:?LASTFM_API_KEY is required}
    ports:
      - 3000:3000
    restart: unless-stopped